### PR TITLE
Post effects

### LINKED ISSUE #23: Add post processing effects (Bloom, SSAO, vignette, etc.)

### PR DESCRIPTION
**Pull request by SpudTatterson**
Closes #23

### CODE REVIEW

**Comment by dandeduck** [comment]
I've finally finished my branch

**Comment by dandeduck** [comment]
I will back merge and fix conflicts shortly

**Comment by dandeduck** [comment]
Ok, I resolved it. So the `Volume` component is supposed to be on the `Player` GameObject correct?

**Comment by dandeduck** [comment]
@SpudTatterson  and btw, to communicate that the PR has been reviewed and is waiting for an update (code or just a comment) the PR is closed. After you've addressed the issue/question, you should re-open it.

**Comment by SpudTatterson** [comment]
Yes

**Review by dandeduck — CHANGES_REQUESTED** [review]
Remove unused package, please.

**Review by dandeduck — APPROVED** [review]
All good, merge at you convenience.

**Pull request merged**
